### PR TITLE
Directly using an RDKit mol with the `mol_col` parameter

### PR DESCRIPTION
**Pull request by fredrikw**
Added an option "mdl_col" to use coordinates allready present in DataFrame or other input. There are probably other ways to implement this, but I needed a way to draw molecules with the coordinates prepared in advance.

### CODE REVIEW

**Comment by cbouy** [comment]
Thank you for your contribution, I like the idea of using pre-existing coordinates!
I think it would make more sense to directly store an RDKit mol in the internal DataFrame and directly use that for drawing instead of relying on a SMILES/MDL column then converting it to a mol then drawing it.
This way it should be possible to add arbitrary annotations on atoms or bonds.
I'll try some changes and come back to you.

**Comment by fredrikw** [comment]
That sounds like a very good alternative! This was simpler to me since I had the Molblock in the dataframe allready :-)

**Comment by cbouy** [comment]
I've made the changes, can you tell me if it integrates nicely with your use case ?

Assuming your dataframe has a column named "MDL" containing a series of MolBlock, you should be able to do 
```python
mols2grid.display(
    df.assign(mol=lambda x:
              [Chem.MolFromMolBlock(mdl) for mdl in x["MDL"]]),
    mol_col='mol')
```

**Comment by fredrikw** [comment]
I have now tested and it is working great in my use case!

**Comment by cbouy** [comment]
Thank you @fredrikw 👍

**Pull request merged**
